language: php
php:
- '5.6'
- '7.0'
- '7.1'
- nightly
env:
  matrix:
  - DB=mysql
matrix:
  allow_failures:
  - php: nightly
before_script:
- phpenv config-rm xdebug.ini
script:
- phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd .. && zip -r tpl_ttactua_mobile.zip ttactua_mobile -x \*.git\* \*tests\* *travisci-phpunit.xml* *.travis.yml*
deploy:
  provider: releases
  file: tpl_ttactua_mobile.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: HVboK8WrSbnaxG1dHbPuGKLkYMnXaD8nxY2H4zuIACxQz4+60ByUtTb1Az4KT9xdM6wBQWEBU3vvKVcx3FmTyCJuVdpimqlzB2RiWUW3aLpNWr2ZSROyPwgoK1BfCKoILULp+0JP1gaThSwSw4YTqVLOnDlnWLj5fBU6ZMHEAAEHJZ/ZYoqt+7EVeHjvbl/tvEgUcNQApuNfEEOH3GQRqPNlyg91ICsrbqhDKG5iBjemU17kP5Wtc/XgGjpSrB8FQSVIAH9U4cgu9CVzklcOB8bX0Wlu1qa8B6bFlWiijbLOPggHmUvTgcaAWmTtRsY/L/wMZTaHlnDEhGPV/lPzJ9hTctRRt5U6cPQcxCOte1mN3jw2Hk8hTdjbuH2neGeDs4n8hT90qEtSkqDl++3mMaJsHna1g4mzF833qs56+KwUc/aFdbezE5sdI3+HAGDUjU8MDUiN/TaJcGmLo6QHLQtLsGOx61SfE0U3BP4f5tbGljtgstpExuSxPp+ZL+NNvj+mAbBD1HEjAVAdkiKofb3N8zerooHEJAl4Sh7kQjXR5aykyc/KirTuBk+adr/bulOtcTPKvVAi5gaSIHXM4kbfRx1JJHVxVXOeh6heDyoLtWiOVBw9RZ7SlZZgm/8z/BR6amfbObi8btT6/GD1ayWbi52ZnR8KhoZA2fguppE=
