language: php
php:
- '5.6'
- '7.0'
- '7.1'
- nightly
env:
  matrix:
  - DB=mysql
  global:
  - secure: incn8WYlX9oEmmVRnWNsAuXJndcU4NY1clQuQJLgeeEVK/Dkm612nGWBij82BbOLW4LPYizc3JbuBAX/Iy3olyEmlCdGcuyDRzX2YmoyxpH6b4WT3SQ2ASQa6rQOhpNo377t5US9cCXdtlwAyoeYlLuxTeA47F0wMwUjkj8b5c6922TnfhTbZ518D1DWCR2FgRFl6NXCHAqIvk8rL8sTStemgV7HdS6MDaWNEXVl6j+a42MK7uWoJxsemBpoehr7I5R244Adm9sU3fnEgH/jQ8L8WgxAPWv4O0z/dXfIjoHanNX+yDQYGyU+xOJtSMPJBI8LMDaypRMOi4uC4mJ0LugZ3K3ktAwGFenx+/87yfFJ60seHdbbsnr0T/J4vg+v0xDz3v9TtJK2oEUEZf4hADgrCjZ/0uZogdQAQ7KASc3dfNfrDEGQZuGmVVjYhO5cJUjUKVYb+8/qJMrjWbYmHzgqSCWyKiBZ+WnEQJj90/DfBHHqYtSVJ6ppzrGBR0S/z9TWAcLAtEXO/fp4jBqhIY4tUmT8hNFsQV380ol+rU+KrnZM5WCtkWU13C+UWSx66QuQXKoaRNBt71SICRxduTPA01z1BsmQlafEFYyqIWQCbblual/PrMRymQViyF3eRsRMgVLt+03ljfPqj3ZavUN83XYNej7yYFC1Sie26eE=
  - secure: oP5s9VE35yDrwTmcqUsX155POgjAV4qWXYgGk6rjXbnk2Za1JIyX2ua1haAbbHhaXDtZjwenmWPVerN9cK1vX8A4ugt0ymS40lhvX+bAfkF5E7Bme6INzZwkU3LWhjsGcwNR3s33aBCng9Wi9kyxyPioRS9M/sE4rNOisBKYjygZ4CnhFS6cY3qQKpJlCGJS6XHRTDvx6j9lYFWxaOuzWvSaQ1e4kz/3lQyQy2w/gisWgFGfWJPYzcXVmYOB/Vm5RjWtKq3urRZ1T4jQJ6aASHZNdw+ncpZ9egt0EDqExIRHpkqvkBxd+Rf6dMbOsj4Xl9IQpT6DeqHLDB9OuD36k+8v6kkEWGtGFjgiotbYU7WHsz6jQtXROC9G1vMG+BavsQ9xkA3tz7VEEIcboWq2j2KEGeoycbJWqyBkU67HuQS2g/Qyr13j/it0VjPu3pwgirUInLN7JOFZ1lxw/AIo8N426j906nZzfxgOBauOWbxgFSz04MvgpiTKiz+rbiy7K7j66VRTQeTN8gsYSICPxMkab/18d80TEgtc6SGdwN4dZMB8w5rXnnqeSGfhlnl6oblljm0b3+uLfm6DqGb2floOV6bcNQpRAgV+hzgZR2cBbBKPtrASIvr4hEdf+wr4+lvSj7M4Gerxmn3cIkHYh1kO5ErPdWnca4gsalFWBxQ=
matrix:
  allow_failures:
  - php: nightly
before_script:
- phpenv config-rm xdebug.ini
script:
- phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd ..
- zip -r tpl_ttactua_mobile.zip ttactua_mobile -x \*.git\* \*tests\* *travisci-phpunit.xml*
  *.travis.yml* *pkg_ttactua_mobile.xml* *tpl_ttactua_mobile.xml*
- git clone https://github.com/ndeet/plg_system_less.git plg_system_less
- zip -r plg_system_less.zip plg_system_less -x \*.git\* *.gitignore*
- zip -j pkg_ttactua_mobile tpl_ttactua_mobile.zip plg_system_less.zip ttactua_mobile/pkg_ttactua_mobile.xml
deploy:
  provider: releases
  file:
  - tpl_ttactua_mobile.zip
  - plg_system_less.zip
  - pkg_ttactua_mobile.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: YFNRm57erCp0zwqM813pmMP0Y70vjW57ILQ8wf0b601Jfjc58g+5DhpO8CTIVjnB6uqbhqcr0mJQhlBgFUTMFy8DqQ0jR58elIjtE6fFxjtJ+1aL2j+DlM4Bd2AaKxtxCnRrrDXJB3zWDHpDgvvhNImphSCkbuTvcR4MlGMrQvtHqHc6RTUp+k98ir1PS0ShLXincMiJzidwAr8UVd/qS1SPNPjCFXSSPK6qPtigslFBAUxqMs4EjshQZj0oD7okAXviKmQar02T9ydy/+04IHb+71UGITQl2L3RqtzSRPef4fH2w+kI1qQ6NdgjsDjQN8q4yYx97viWkcYys9Dr9MrUn2Q8Lg0OP+2X1hpeab3KuATg2E/5NK2Fagj5CCsu2WOtpzODTMPt9zklPBzpx5R/HoyfW8nFrZqITMlE1RqCg8XDWIoVyrs7qsezEw67FGS0brzIRjTsgUMkexBG3ELsc+7tBCmrw83WVNJU2ywQ3r1BvFwFJ84Or70vlLTCT/hH1yfU3kG2OtvYjJtX800htJ3nVwyhIIz7HE2bzNq+1Jaxf1ul/o8NLsopRuqFdRu9ee1J5DQYpxzly3qlD8McnEnP3xZdpLEQqHkXupdpJKbhuVH/um2CWSQA15YPrEZ6Japsmq+tl2msVpOdpgZwTybQzKFlOM2wQhU+8B4=
after_deploy: curl -T tpl_ttactua_mobile.xml -u $FTP_USER:$FTP_PASSWORD ftp://gilebabe.webhosting.be/
